# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
solc = "0.8.29"
auto_detect_solc = false
auto_detect_remappings = false
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false
evm_version = "cancun"
fuzz = { runs = 1_000 }
gas_reports = ["*"]
libs = ["lib"]
optimizer = true
optimizer_runs = 200
out = "out"
script = "script"
src = "src"
test = "test"
ignored_warnings_from = ["node_modules", "lib", "test"]
gas_limit = "18446744073709551615" # u64::MAX
via_ir = true

[profile.default.optimizer_details]
yul = true

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[fmt]
bracket_spacing = true
int_types = "long"
single_line_statement_blocks = "single"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 2
wrap_comments = true
sort_imports = true
code-complexity = 20

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", chain = 1, url = "https://api.etherscan.io/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 1115542, url = "https://api-sepolia.etherscan.io/api" }

arbitrum = { key = "${ARBISCAN_API_KEY}", chain = 42161, url = "https://api.arbiscan.io/api" }
arbitrum-sepolia = { key = "${ARBISCAN_API_KEY}", chain = 421613, url = "https://api-sepolia.arbiscan.io/api" }

base = { key = "${BASESCAN_API_KEY}", chain = 8453, url = "https://api.basescan.org/api" }
base-sepolia = { key = "${BASESCAN_API_KEY}", chain = 84532, url = "https://api-sepolia.basescan.org/api" }

polygon = { key = "${POLYGONSCAN_API_KEY}", chain = 137, url = "https://api.polygonscan.com/api" }
polygon-amoy = { key = "${POLYGONSCAN_API_KEY}", chain = 80002, url = "https://api-amoy.polygonscan.com/api" }

[fuzz]
runs = 1000